# Use root/example as user/password credentials
version: '3.1'
name: 'pet-sa'
services:
  db:
    image: mysql:8.3.0
    container_name: mysql-3.1-pet-s.a
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: pet-sa
      #MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
    ports:
      - 3306:3306
    volumes:
      - data:/home/ddebian/CODE/DOCKER/volumes
volumes:
  data:


## execute:  docker compose -f mysql.yaml up -d