mysql:
  username: root
  password: rootroot
  address: localhost
  port: 3306
  database: pet-sa
handlers:
  port: 8081

graphql:
  go get github.com/99designs/gqlgen/codegen/config@v0.17.45
  go get github.com/99designs/gqlgen/internal/imports@v0.17.45
  go get github.com/99designs/gqlgen/internal/imports@v0.17.45
  go get github.com/99designs/gqlgen@v0.17.45