// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Client struct {
	Cedula    string `json:"cedula"`
	Nombres   string `json:"nombres"`
	Apellidos string `json:"apellidos"`
	Direccion string `json:"direccion"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
}

type Medicine struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Dosis       string `json:"dosis"`
}

type Mutation struct {
}

type NewClient struct {
	Cedula    string `json:"cedula"`
	Nombres   string `json:"nombres"`
	Apellidos string `json:"apellidos"`
	Direccion string `json:"direccion"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
}

type NewMedicine struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Dosis       string `json:"dosis"`
}

type NewPet struct {
	Nombre        string  `json:"nombre"`
	Raza          string  `json:"raza"`
	Edad          int     `json:"edad"`
	Peso          float64 `json:"peso"`
	CedulaCliente string  `json:"cedulaCliente"`
}

type NewRecipe struct {
	IDMedicamento int `json:"idMedicamento"`
	IDMascota     int `json:"idMascota"`
}

type Pet struct {
	Nombre        string  `json:"nombre"`
	Raza          string  `json:"raza"`
	Edad          int     `json:"edad"`
	Peso          float64 `json:"peso"`
	CedulaCliente string  `json:"cedulaCliente"`
}

type Query struct {
}

type Recipe struct {
	IDMedicamento int `json:"idMedicamento"`
	IDMascota     int `json:"idMascota"`
}

type UpdateMedicine struct {
	ID          int    `json:"id"`
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Dosis       string `json:"dosis"`
}

type UpdatePet struct {
	ID            int     `json:"id"`
	Nombre        string  `json:"nombre"`
	Raza          string  `json:"raza"`
	Edad          int     `json:"edad"`
	Peso          float64 `json:"peso"`
	CedulaCliente string  `json:"cedulaCliente"`
}
