// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Client struct {
	Cedula    string `json:"cedula"`
	Nombres   string `json:"nombres"`
	Apellidos string `json:"apellidos"`
	Direccion string `json:"direccion"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
}

type GeneralClientReport struct {
	Mascotas         []*PetReportClient `json:"mascotas"`
	CedulaCliente    string             `json:"cedula_cliente"`
	NombresCliente   string             `json:"nombres_cliente"`
	ApellidosCliente string             `json:"apellidos_cliente"`
}

type Medicine struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Dosis       string `json:"dosis"`
}

type Mutation struct {
}

type NewClient struct {
	Cedula    string `json:"cedula"`
	Nombres   string `json:"nombres"`
	Apellidos string `json:"apellidos"`
	Direccion string `json:"direccion"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
}

type NewMedicine struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Dosis       string `json:"dosis"`
}

type NewPet struct {
	Nombre        string  `json:"nombre"`
	Raza          string  `json:"raza"`
	Edad          int     `json:"edad"`
	Peso          float64 `json:"peso"`
	CedulaCliente string  `json:"cedulaCliente"`
}

type NewRecipe struct {
	IDMedicamento int `json:"idMedicamento"`
	IDMascota     int `json:"idMascota"`
}

type Pet struct {
	Nombre        string  `json:"nombre"`
	Raza          string  `json:"raza"`
	Edad          int     `json:"edad"`
	Peso          float64 `json:"peso"`
	CedulaCliente string  `json:"cedulaCliente"`
}

type PetReport struct {
	Recetas       []*RecipePetReport `json:"recetas"`
	EdadMascota   string             `json:"edad_mascota"`
	PesoMascota   string             `json:"peso_mascota"`
	RazaMascota   string             `json:"raza_mascota"`
	NombreMascota string             `json:"nombre_mascota"`
}

type PetReportClient struct {
	NombreMascota     string `json:"nombre_mascota"`
	DosisReceta       string `json:"dosis_receta"`
	DescripcionReceta string `json:"descripcion_receta"`
}

type Query struct {
}

type Recipe struct {
	IDMedicamento int `json:"idMedicamento"`
	IDMascota     int `json:"idMascota"`
}

type RecipePetReport struct {
	Medicamento       string `json:"medicamento"`
	DosisReceta       string `json:"dosis_receta"`
	DescripcionReceta string `json:"descripcion_receta"`
}

type UpdateMedicine struct {
	ID          int    `json:"id"`
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Dosis       string `json:"dosis"`
}

type UpdatePet struct {
	ID            int     `json:"id"`
	Nombre        string  `json:"nombre"`
	Raza          string  `json:"raza"`
	Edad          int     `json:"edad"`
	Peso          float64 `json:"peso"`
	CedulaCliente string  `json:"cedulaCliente"`
}
